.github/workflows/test.yaml, rebar.config, src/khepri_path.erl, test/prop_path_operations.erl, test/prop_state_machine.erl, test/test_ra_server_helpers.erl
This testing is not that extensive at this time. For instance, the Khepri state machine is tested with simple paths without any conditions. However, this allowed us to discover a couple bugs in the way paths are converted back and forth between their native and their string-based forms.
=> Test: Add property-based testing for `khepri_path` and `khepri_machine`

.github/workflows/test.yaml, rebar.config.script
They are expensive to generate and they are perfect candidates for caching because they do not change for a given version of Erlang.
The `rebar.config.script` file was reorganized because an earlier version of that patch depended on a change in that file. This is no longer needed, but I kept the reorganization to make it easier to extend `rebar.config.script` in the future.
=> GitHub Actions: Cache Dialyzer PLT files

src/khepri_fun.erl, src/khepri_tx.erl, test/tx_funs.erl
This fixes the auto detection of R/W nature when a transaction function has another lambda in its environment.
Here is an example added to the testsuite:
```erlang
Fun = fun() -> khepri_tx:delete([foo]) end,
khepri_tx:to_standalone_fun(
fun() -> Fun() end,
auto),
standalone_fun)).
```
In this scenario, the lambda passed to `khepri_tx:transaction/2` is considered read-only because it doesn't call `khepri_tx:put/2` or `khepri_tx:delete/1`. However, it calls another lambda from its environment which calls one of these functions.
Before this patch, this was undetected because the `validate()` callback was called for the top-level lambda first. The callback would considered the lambda read-only and stop, skipping the second lambda from the environment entirely.
Now, the code analyzes the …
=> Fix R/W auto detection with lambdas in the transaction function's environment

src/khepri_utils.erl, test/display_tree.erl
Map keys are unordered and the function didn't handle that. So if in `maps:fold/3`, `[foo, bar]` was handled before `[foo]`, the code would hit an assertion and crash.
Now it correctly merges `[foo]` node props with its existing child nodes.
This was reported by @mkuratczyk while testing the integration of Khepri in RabbitMQ.
=> khepri_utils: Handle unordered keys in `flat_struct_to_tree/1`

src/khepri_path.erl, test/queries.erl, test/simple_get.erl
This cleans any use of `?ROOT_NODE` or `?THIS_NODE` in the path. Otherwise the function would return a different result if these macros were prepended to `?STAR` or `?STAR_STAR` for instance, even though the meaning of the path is exactly the same.
I'm still not very happy with this heuristic to determine if the root node properties should be included in a get. Another solution would be to require an explicit `?ROOT_NODE` in the path to include its properties in the result.
=> khepri_path: Call realpath/1 in pattern_includes_root_node/1

src/khepri_tx.erl
I couldn't figure out a testcase using this instruction, but a transaction in RabbitMQ happens to use one.
This was reported by @mkuratczyk.
Fixes #13.
=> Transactions: Support `set_tuple_element` Erlang instruction

doc/overview.edoc, src/internal.hrl, src/khepri.erl, src/khepri_condition.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tx.erl, test/db_info.erl, test/keep_while_conditions.erl, test/machine_code_called_from_ra.erl
The reason is that we want to "keep a node while a condition remains true". It is clearer than "keep a node until a condition becomes false" which was my initial thinking.
=> Rename "keep until" conditions to "keep while" conditions

README.md, doc/overview.edoc, include/khepri.hrl, src/khepri.erl, src/khepri_condition.erl, src/khepri_machine.erl, src/khepri_tx.erl, test/conditions.erl, test/db_info.erl, test/delete_command.erl, test/display_tree.erl, test/keep_while_conditions.erl, test/machine_code_called_from_ra.erl, test/prop_state_machine.erl, test/put_command.erl, test/queries.erl, test/root_node.erl, test/transactions.erl, test/tx_funs.erl
The `?NO_PAYLOAD` macro becomes simply the `none` atom.
The `?DATA_PAYLOAD(Data)` one becomes the `#kpayload_data{data = Data}` record.
This allows some compile time verification and adds the ability to specify the payload types (for Dialyzer).
=> Replace macros by records to represent payloads

src/khepri_machine.erl
I planned to use it for event subscription, but I will probably do something else. Meanwhile, the log message is really noisy and useless. So let's remove that code for now. If it is useful at some point, it is easy to add it back.
=> khepri_machine: Remove temporary aux machine code

src/khepri_fun.erl
... written in the Elixir shell (`erl_eval` anonymous functions).
In the `erl_eval` anonymous function's env, the first element in the tuple represents the function bindings. Erlang is using a list, but Elixir is using a map.
`erl_eval_fun_to_asm()`, which does pattern matching to ensure there is no bindings, expected an empty list. Now it accepts an empty map as well to support the Elixir case.
Note that bindings are still unsupported.
Reported by @mkuratczyk.
Paired with @mkuratczyk.
=> khepri_fun: Fix extraction of Elixir anonymous functions

.github/workflows/test.yaml, rebar.config
In order to run Dialyzer on testsuites, I changed `extra_src_dirs` to include the test directory as well. Unfortunately, after adding the property-based testcases, I had to add PropEr to the dependencies...
The other solution is to explicitly run Dialyzer under the `test` Rebar profile. I don't know any way to tell Rebar to use that profile by default with Dialyzer, so one has to remember to use it on the command line.
The `check` alias does not set any specific profile, so Dialyzer is executed on the library only or the user must specify the `test` profile on the command line. The problem with the latter is that it will affect other commands such as `xref`.
=> Remove hack to run dialyzer on testsuites

.gitignore, rebar.config, src/khepri.app.src
Fixes #26
Explicitly list files and directories to include to ensure `rebar3 hex publish` includes the `mix.exs` file.
https://hex.pm/docs/rebar3_publish#adding-metadata-to-code-classinlinesrcltmyappgtappsrccode
@dumbbell I'm not sure how you're publishing this project to `hex.pm`. We should discuss.
=> Configure project to include "mix.exs" when published via "rebar3 hex publish"

src/khepri_fun.erl, test/mod_used_for_transactions.erl, test/tx_funs.erl
Let's take the following code:
```erlang
-export([outer_function/2]).
outer_function(#my_record{field = ...} = MyRecord, Term) ->
(...),
inner_function(MyRecord, Term);
outer_function(_, _) ->
(...).
inner_function(#my_record{field = ...} = MyRecord, Term) ->
(...);
inner_function(_, _) ->
(...).
```
Both `outer_function/2` and `inner_function/2` take a tuple as their first argument and do a pattern matching with it. `outer_function/2` is exported and `inner_function/2` is only called by `outer_function/2`.
In this situation, the compiler may perform an optimization on `inner_function/2`: it is sure that the function will take a tuple of the expected form because it was already checked in `outer_function/2` and it is the only caller. Therefore, it will skip any verifications and will read …
=> khepri_fun: Add guessed `var_info` annotations to assembly

src/khepri_fun.erl, src/khepri_tx.erl, test/tx_funs.erl
`beam_asm` decodes several bitstring matching instructions incorrectly. Sometimes, it's just the field flags which are not decoded. Unfortunately, sometimes, instruction arguments order is incorrect or the argument does not have the form expected by the compiler.
Now, `pass1_process_instructions/3` starts by patching those instructions before doing anything else with them. This way the rest of the code handles correct instructions (from the point of view of the compiler). A second benefit is that if `beam_disasm` is fixed, Khepri will continue to work.
=> khepri_fun: Patch incorrectly decoded instructions

src/khepri_fun.erl, test/tx_funs.erl
:wave: hello!
The disasm scanning to lint transaction functions is super cool!
I noticed the select_tuple_arity instruction doesn't get its cases' labels rewritten, so code that has a case statement branching on the arities of tuples will make the `compile:forms/2` call error out with a message talking about undefined labels. That instruction has the same shape as select_val, so I have it re-using that function clause to rewrite the labels.
What do you think?
=> rewrite case labels in select_tuple_arity instruction

src/khepri_fun.erl, src/khepri_tx.erl, test/tx_funs.erl
builds on #39 to decode more bitstring-matching instructions that are not decoded properly by beam_disasm
=> patch more incorrectly decoded bitstring-matching instructions

rebar.config
For case when last version(`7.0.1`) of project plugin `rebar3_hex` is used for publication of documentation to `hex.pm`, can be received second warning:
```sh
$ rebar3 hex publish docs
...
===> Verifying dependencies...
===> docs argument given, will not publish package
===> No documentation provider was configured, docs will not be generated
```
For this case was added provider as suggested in `rebar3_hex` documentation.
=> Add documentation provider

src/khepri_fun.erl, src/khepri_tx.erl, test/tx_funs.erl
See [this](https://github.com/erlang/otp/blob/df48c260e74c3e9058ff8681ce9f554e6fa0fe34/lib/compiler/src/beam_asm.erl#L360-L361) line in beam_asm.
The `raise` instruction needs to be translated to a `bif`. Luckily
the arguments line up very well so it's an easy translation. It was
a bit tough writing a test case that the compiler wouldn't optimize
the raise/try out of, I ended up using the send+receive technique from
a few test cases down.
=> add translation for 'raise' BIF

src/khepri_tx.erl, test/tx_funs.erl
These instructions can be used to smuggle impure function calls past the linter like so:
```erl
Module = erlang,
Module:send(Pid, msg).
```
It's notable that this can make usage in Elixir less convenient because the map syntax can be interpreted as apply:
```elixir
defmodule Foo do
def foo(map_or_module), do: map_or_module.utc_now
end
iex> Foo.foo(%{utc_now: 0})
0
iex> Foo.foo(DateTime)
~U[2022-02-09 15:09:30.338756Z]
```
So elixir map access instead needs to use `Map.get/3`/`Map.fetch/2`/etc.
=> deny apply/1 and apply_last/2 instructions

src/khepri_fun.erl, test/tx_funs.erl
supersedes #45
closes #44 
This PR:
- moves the annotation-guessing for tuples and maps into `pass1_process_instructions/1`
- guesses `accepts_match_context` annotations for `bs_start_match*` instructions
- refactors the add_comment_* functionality to add annotations at exact indices within instruction lists upon `compile:forms/2` failure
This is still WIP while I figure out a good way to handle the hard-coded register :thinking:
=> preemptively infer var_info annotations

src/khepri_fun.erl, test/mod_used_for_transactions.erl, test/stored_procs.erl
Line information comes from the "Line" chunk in the beam module. This is not decoded by `beam_disasm` and the `line` instructions it produces only have the index inside that "Line" beam chunk.
So far, we needed to get rid of all those `line` instructions because they were invalid for the compiler. It meant that frames in stacktraces pointing to an extracted function had no location. This made any sort of debugging quite difficult.
Here is an example without this patch:
```
%% Based on the following function:
%%     crashing_fun() ->
%%         throw("Expected crash").
1> Fun = khepri_fun:to_standalone_fun(fun mod:crashing_fun/0, #{}).
2> khepri_fun:exec(Fun, []).
** exception throw: "Expected crash"
in function  kfun__mod__crashing_fun__33048370:run/0
```
Now, we decode the "Line" beam …
=> Decode "Line" chunk and expand `line` instructions

src/khepri_fun.erl, test/tx_funs.erl
The `select_tuple_arity` is used in the following code for instance:
```erlang
case Tuple of
{ok, _, _}   -> true;
{error, _}   -> false;
{timeout, _} -> false
end
```
In other words, the VM can simply verify the arity of the tuple to decide between `true` and `false` if the atom in the first position was implicitly verified earlier in the code.
`beam_validator` expects the annotation to specify a tuple without any specific arity.
=> khepri_fun: Add `select_tuple_arity` type annotation

src/khepri_fun.erl, test/tx_funs.erl
This is a follow up for removing the hard-coded register `FIXME` (https://github.com/rabbitmq/khepri/pull/49#issuecomment-1039196029). Sorry the title is so long and jargon-y 😅
A simplification of the problem is that function `A` calls function `B` calls function `C`. `A` passes an argument to `B` that `accepts_match_context`, but `B` doesn't have any annotations for its parameters, so the `beam_validator` emits an error on the call instruction saying: `no_bs_start_match2`.
<details><summary>I got a bit derailed looking into this by function <code>C</code>...</summary><br>
In the test case fixtures, `C` has a parameter that `accepts_match_context`, so I thought that in order to fix this, we would need to determine the types of each function in the call graph (which naively seems easy …
=> khepri_fun: propagate argument annotations to callee in bs_no_start_match2 validation failures

src/khepri.erl, src/khepri_app.erl, src/khepri_machine.erl, test/app.erl, test/favor_option.erl, test/test_ra_server_helpers.erl
`khepri_machine:get/3` and `khepri_machine:transaction/4` now accept a new option in the options map: `favor`.
`favor` indicates what the caller prefers between freshness of the data and low latency of the query. Accepted values are:
* `consistency`: it means that a "consistent query" will be used in Ra. It will return the most up-to-date piece of data the cluster agreed on. Note that it could block and time out if there is no quorum in the Ra cluster.
* `compromise`: it performs "leader queries" most of the time to reduce latency (though latency will still be higher than "local queries"; see below), but uses "consistent queries" every 10 seconds to verify that the cluster is healthy. It should be faster but may block and time out like `consistency` and still return slightly out-of-date …
=> Let the caller choose between consistency and low latency for queries

doc/overview.edoc
A new section to the documentation was added to clarify that Khepri triggers are not the same as RDBMS ones, despite the same name. Triggers in Khepri can't mess with the database content directly.
This fear comes from some feedback after the announcement of triggers. The person who expressed that fear was reassured after knowing that difference.
While here, fix a typo in the paragraph above the added section.
Fixes #58.
=> Documentation: Clarify the difference for triggers between Khepri and RDBMS

src/khepri_fun.erl, test/tx_funs.erl
It looks like this `{test, test_arity, _, _}` instruction needs the `t_tuple` type inference similar to `get_tuple_element/3` and `select_tuple_arity/3`. The instruction seems to show up when the compiler knows ahead of time that the input will be a tuple but isn't sure of the arity and needs to branch on the arity.
=> infer type annotation for `test_arity` test instruction

src/khepri.erl, src/khepri_machine.erl, test/async_option.erl, test/favor_option.erl, test/test_ra_server_helpers.erl
`khepri_machine:put/5`, `khepri_machine:delete/3` and `khepri_machine:transaction/4` now accept an options map with a single option called `async`.
`async` indicates if the caller wants a synchronous or an asynchronous command. Accepted values are:
* `true' to perform an asynchronous low-priority command without a correlation ID.
* `false' to perform a synchronous command.
* A correlation ID to perform an asynchronous low-priority command with that correlation ID.
* A priority to perform an asynchronous command with the specified priority but without a correlation ID.
* A combination of a correlation ID and a priority to perform an asynchronous command with the specified parameters.
The default is currently set to `false` (i.e. all commands are synchronous).
Note that to clarify options, …
=> Let the caller select between sync and async commands (put, delete or read-write transaction)

.github/workflows/trigger-benchmark.yaml
The benchmark is managed in a separate repository:
https://github.com/rabbitmq/khepri-benchmark
Results should be publicly visible on the associated GitHub Page:
https://rabbitmq.github.io/khepri-benchmark/
=> GitHub Actions: Trigger benchmark run after a commit is pushed to the `main` branch

src/khepri_condition.erl, src/khepri_machine.erl, src/khepri_path.erl, src/khepri_tx.erl, test/machine_code_called_from_ra.erl, test/path_operations.erl, test/transactions.erl
This was the case for the "simple API" in `khepri` only so far. But this is convenient to be able to use string-based paths anywhere. It also improves the consistency of the API.
As a consequence, `khepri_path:from_string/1` accepts both string-based and regular paths and returns a regular path. Now unnecessary, `khepri_path:maybe_from_string/1` and `khepri_path:component_from_string/1` were removed.
`khepri_path:component_to_string/1` is still there but made internal. It's not public anymore.
=> Accept string-based paths in `khepri_machine` and `khepri_tx`

src/khepri_path.erl, test/path_operations.erl, test/prop_path_operations.erl
First, atoms are represented as `:atom`. Binaries are simpler and represented as `binary` (the prefix and suffix are gone).
Then, atoms and binaries are percent-encoded in order to make them compatible with URIs. For instance, if an atom or binary contains a forward slash, it can be encoded as `%2F`.
Note that the empty atom `''` will be represented as `":"`, however the empty binary `<<>>` can't be represented.
Here a some examples:
| String-based path | Regular path                             |
|-------------------|------------------------------------------|
| `"/:foo/:bar"`    | `[foo, bar]`                             |
| `":foo/:bar"`     | `[?THIS_NODE, foo, bar]`                 |
| `"./:foo/:bar"`   | `[?THIS_NODE, foo, bar]`                 |
| `"/foo"`          | `[<<"foo">>]` …
=> khepri_path: Change syntax of string-based paths

src/khepri_fun.erl, test/sf_cache.erl
The cache key is the anonymous function's module, function name and arity, the options passed to `to_standalone_fun()`, plus the checksum of the module holding it.
The cache value is the standalone function, the checksums of all modules called directly or indirectly by the function including the modules referenced by callbacks in the options map.
This cache allows to skip both passes and the compilation. A quick benchmark showed the following rates for the same transaction executed in a loop by 140 concurrent processes:
* without cache: 20k transactions per second
* with cache: 60k transactions per second
The transaction only did a `khepri_tx:put/2` call. As a comparison, a direct call to `khepri_machine:put/3` leads to 80k insertions per second.
**TODO**: The cache is never cleaned …
=> khepri_fun: Cache compiled standalone function

src/khepri_machine.erl, test/keep_while_conditions.erl
Added test that reproduces this use case, using an `if_node_exists condition` on `keep_while` that must be exercised
=> Fix typo handling deleted nodes on aftermath

rebar.config, src/khepri_fun.erl, src/khepri_tx.erl
This includes at least the support of the new `bs_create_bin` instruction.
=> Support Erlang/OTP 25

.github/workflows/test.yaml
This is currently based on Erlang/OTP 25.0-rc3 release candidate.
=> Enable Erlang/OTP 25 in CI

src/khepri.erl, src/khepri_tx.erl, test/simple_get.erl, test/transactions.erl
This is the same as `get_data/{1,2,3}` except that it takes a default value as argument to return if the tree node does not exist, has no data or holds a stored procedure.
=> khepri: Add `get_data_or/{2,3,4}`

src/khepri_path.erl, test/path_operations.erl
This is especially handy for Beam languages which use Erlang binaries to implement strings, such as Elixir or Gleam.
To achieve that, `khepri_path:from_string/1` is expanded to accept Erlang binaries. The implementation is very basic: the binary is converted to a list.
We also introduce `from_binary/1` which just calls `from_string/1`. So they both accept all representations of paths. `from_binary/1` is for convenience and to make it clear that Erlang binaries are accepted.
`to_string/1` will always return an Erlang string however. To produce a binary, there is now `to_binary/1`.
Fixes #92.
=> Accept binaries for Unix-like paths

src/internal.hrl, src/khepri.erl, src/khepri_condition.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_path.erl, src/khepri_tx.erl
The main improvement of this branch is the redefinition of the `path()` and `pattern()` types. We are now explicit on which types of path are accepted in which places.
The types are:
* `native_path()`, the internal representation made of atoms, binaries and, for patterns only, conditions.
* `unix_path()`, the Unix-like path representation, which can be either an Erlang string (list of Unicode characters) or an Erlang binary (which can be any UTF encoding).
The `path()` type is now the union of both `native_path()` and `unix_path()`.
Likewise for path patterns with `native_pattern()`, `unix_pattern()` and `pattern()`. Note that in the case of patterns, only a few conditions can be represented in the Unix-like path pattern.
See #92 for the discusion which triggered this change.
=> Redefine the `path()` type

src/internal.hrl, src/khepri.erl, src/khepri_condition.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tx.erl, test/machine_code_called_from_ra.erl, test/transactions.erl
Now the following `keep_while` conditions are equivalent:
```erlang
%% Using a native path.
khepri:put(
StoreId, Path, Value,
#{keep_while => #{[?THIS_NODE] => Condition}}).
```
```erlang
%% Using a Unix-like string path.
khepri:put(
StoreId, Path, Value,
#{keep_while => #{"." => Condition}}).
```
```erlang
%% Using a Unix-like binary path.
khepri:put(
StoreId, Path, Value,
#{keep_while => #{<<".">> => Condition}}).
```
There is a second commit which fixes the definition of the `keep_while` option in the `put()` family of functions. It was set to an internal structure of the state machine instead of `khepri_condition:keep_while()`. That internal structure type is made private again as a consequence.
=> Accept Unix-like paths in `keep_while` conditions

include/khepri.hrl, src/khepri_condition.erl, test/conditions.erl
In other words, the new `conditions` field of the `#if_data_matches{}` record can be used to set the `MatchCondition` field of the `{MatchHead, MatchCondition, MatchBody}` pattern matching structure.
Here is an example of a conditional pattern match:
```erlang
%% The data must be of the form `{age, Age}' and `Age' must be an
%% integer greater than or equal to 18.
#if_data_matches{pattern = {age, '$1'},
conditions = [{is_integer, '$1'},
{'>=', '$1', 18}]}.
```
Fixes #85.
=> khepri_conditions: Allow to specify conditions in `#if_data_matches{}`

mix.exs, rebar.config, src/khepri.app.src
The information we need is:
* the application name
* its description
* its version
* its list of dependencies and their version pinning
Everything is available from `src/khepri.app.src` and `rebar.config`.
We do a very basic read of those files. In other words, we don't bother with Rebar profiles, `rebar.config.script` interpretation and so on. We expect a very straightforward list of dependencies, but that should be fine for our needs.
This should solve the problem of keeping `mix.exs` in sync. Indeed, this was triggered by the fact that Ra's version pinning in `mix.exs` was out-of-date for some time now.
=> mix.exs: Read application details from Rebar files

src/khepri_fun.erl, src/khepri_fun.hrl, test/mod_used_for_transactions.erl, test/tx_funs.erl
As part of the `call_fun2` instruction introduced in Erlang/OTP 25, it is apparently possible that the assembly references an anonymous function directly, instead of an MFA. Therefore, we need to follow and extract it like any anonymous functions in the environment.
The extraction is performed when we find such a `move` instruction. The instruction is then updated with a reference to the extracted standalone function. At the time we prepare the reference, that's ok if the module is unavailable in the code server.
When the standalone function is executed later, we simply load all modules stored in the new `literal_funs` list in the `#standalone_fun{}` record. At runtime, the references to those literal funs will be resolved successfully.
The `allowed_higher_order_external_call_test` …
=> khepri_fun: Extract literal funs in `move` instructions

src/khepri.erl, src/khepri_machine.erl, test/simple_get.erl
The new function takes a path pattern and returns the number of tree nodes matching this patttern. The root node is not included in the result.
It is implemented like `khepri:get/{1,2,3}`. Therefore, it is not faster. It will consume less memory though, as the result map is not constructed.
=> Introduce `khepri:count/{1,2,3}` function to count nodes in the tree

src/khepri.erl, src/khepri_path.erl, test/bang_functions.erl, test/sigils.erl
To improve the integration with a pure Elixir code base, this patch brings the following changes:
* `khepri` now exposes "bang functions", i.e. functions named e.g. `get!(StoreId, PathPattern)`. Those functions return the result directly in case of success (i.e. it is not "wrapped" into an `{ok, _}` tuple), or throw an exception.
* `khepri_path` provides the `~p` and `~P` sigils to offer easy path parsing without calling `khepri_path` explicitly.
`erlang:error/1` is used to raise exceptions in both bang functions and sigils, instead of `erlang:throw/1`. The former is the convention in Elixir.
=> Introduce functions targetting Elixir developers

src/khepri_fun.erl, test/helpers.erl, test/tx_funs.erl
The last argument of `get_map_elements` is a list of (possibly tagged) registers. The tagged registers are incorrectly decoded by `beam_disasm` and we must patch them like we do it already in other places. This fixes an error where a standalone function is successfully compiled but fails to load.
While here, we also now handle the absence of `fail` label. Some instructions, which take a label as an argument to jump to if the instruction fails, also accept `nofail` instead of a label. Our patching of fail labels was not taking this case into account. This caused a crash in the function extraction code. This problem was discovered while writing the testcase in this pull request.
=> Work around badly disassembled `get_map_elements` arguments

src/khepri_tx.erl, test/tx_funs.erl
This instruction is generated to throw an exception if for instance the variable in `Variable#myrecord.field` is not a record.
=> khepri_tx: Allow `badrecord` instruction

src/khepri_fun.erl, test/tx_funs.erl
Likewise for `{test, is_tagged_tuple, ...}`.
The last argument is a list of (possibly tagged) registers. The tagged registers are incorrectly decoded by `beam_disasm` and we must patch them like we do it already in other places.
This fixes an error where a standalone function is successfully compiled but fails to load.
=> khepri_fun: Work around bad decoding of `{test, is_tuple, ...}` arguments

src/khepri_fun.erl
In this patch, we fix badly decoded arguments of `{test, ...}` (all of them, not just the ones we saw in the field) and `{bif, ...}`.
=> Work around more badly disassembled instruction arguments

.github/workflows/release.yaml
The workflow is triggered by pushing a tag to GitHub.
=> GitHub Actions: New workflow to publish to Hex.pm

.github/workflows/test.yaml, src/khepri_machine.erl
The `:` character was apparently already denied in flags, but the `codecov` uploader never reported that as an error. Since version 0.2.5, it does and the upload of Khepri's coverage reports broke.
Use `-` instead. This character is already used in the OS name, but that should be ok.
References codecov/uploader#831.
=> Adapt to latest `codecov` uploader

src/khepri.erl, test/simple_get.erl
Before this change, all errors were considered the same and `false` was returned. Now, only the `{error, {node_not_found, _}}` error is interpreted and `false` is returned. All other errors are returned as is.
This helps callers who need to know if the given path is incorrect or if the Ra cluster is degraded.
=> khepri: Return errors in exists(), has_data() and has_sproc()

src/khepri_condition.erl
Path components are valid conditions and may be used within conditions like `if_not`/`if_all`/`if_any`. This change adds a small note on that to the `khepri_condition` module-docs.
=> khepri_condition: Document path components within conditions

src/internal.hrl, src/khepri.erl, src/khepri_cluster.erl, src/khepri_machine.erl
Allows to change snapshot_interval during runtime.
Accepts a map of options so other parameters could be changed later on
=> khepri_machine: add 'configure' command

src/khepri_fun.erl, test/tx_funs.erl
Previously, the checksum calculation in `khepri_fun:to_standalone_fun3/2` assumed that function options were local functions. It's possible to pass external functions as fully qualified captures, for example:
fun khepri_tx:ensure_instruction_is_permitted/1
This change fixes a match error that is raised when passing in external functions as options. When an external function is passed, that function's md5 is used as the checksum.
=> khepri_fun: Allow external funs in options

src/khepri_fun.erl, test/tx_funs.erl
`get_list/3` and `get_hd/2` need type comments that specify the source register as at least a cons-cell: `{t_cons, any, any}` or else the newly compiled code will fail the `beam_validator` checks.
=> Infer typing for get_list/3, get_hd/2

src/khepri_machine.erl, test/triggers.erl
Triggers matching on a pattern which uses conditions applying to grandchildren were previously not detected as triggered from changes to grandchildren nodes.
This change considers conditions which apply to grandchildren in `khepri_machine:does_path_match/4` which fixes the triggering behavior.
=> Fix trigger detection for grandchildren conditions

.github/workflows/test.yaml
There is a regression in EUnit shipped with Erlang 25.1. This regression makes `rebar3 eunit` to fail when it loads testsuites. See erlang/otp#6320.
While we wait for a fix to be committed and a new version of Erlang 25.x to be published, let's pin Erlang 25.0 explicitly.
=> GitHub Actions: Test against 25.0, not the latest 25.x

.github/workflows/test.yaml
We had to do that because EUnit in Erlang 25.1 had a bug which made the Khepri testsuite crash; see erlang/otp#6320.
The bug was fixed in Erlang 25.1.1.
=> GitHub Actions: Stop pinning Erlang 25 version to 25.0

mix.exs
Prior to this change, Mix would not invoke `khepri_app:start/2` when starting the Khepri application (for example in `iex -S mix`). Transaction functions created within IEx would fail since the persistent term `{khepri,skipped_modules_in_code_collection}` was undefined.
This change adds the `application/0` function suggested in the [`mix compile.app`](https://hexdocs.pm/mix/1.14.0/Mix.Tasks.Compile.App.html) documentation. The Erlang `app.src` file already provides the `applications`, `mod`, `env`, and `registered` options necessary to configure the Khepri application, so we inherit the values directly from `src/khepri.app.src`.
=> mix: Add application definition

src/khepri_fun.erl, src/khepri_tx_adv.erl, test/tx_funs.erl
In pull request #134, the `{u,Idx}` argument was discarded and replaced by `{atom, safe}` because the module was already compiled successfully and the register used in the instruction must point to a valid function.
`Idx` is an offset in the Lambda table ("FunT" in the beam chunks). In this patch, we decode this table. This allows us to resolve the label used by `call_fun2` and replace `{u,Idx}` by a valid `{f,Label}`.
This is probably a small optimization of the resulting code, but it closer to what the Erlang compiler would do.
The testcase is expanded to execute the extracted function to make sure it still works.
=> khepri_fun: Resolve label inside `{call_fun2, {u,Idx}, ...}` instruction

src/khepri_fun.erl, test/tx_funs.erl
This option is `add_module_info` and is opt-out.
These functions are used by several debugging and tracing tools in Erlang. This remains an option because they increase the size of a transaction Ra command significantly (about 140 bytes more for the generated module binary).
The `module_info()` functions are extracted from `khepri_fun`. They are simple functions which just call `erlang:get_module_info/{1,2}`.
Fixes #143.
=> khepri_fun: Add an option to add `module_info/{0,1}` to generated module

src/khepri.erl, src/khepri_error.hrl, src/khepri_fun.erl, src/khepri_fun.hrl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_payload.erl, src/khepri_payload.hrl, src/khepri_sproc.erl, src/khepri_tx.erl, src/khepri_tx.hrl, src/khepri_tx_adv.erl, test/simple_tx_misc.erl, test/stored_procs.erl, test/tx_funs.erl, test/tx_sprocs.erl
This patch brings two improvements:
1.  A **transaction function can take arguments**. Arguments are passed as a list of terms to `khepri:transaction()`.
Here is an example:
```erlang
generic_tx(Wood, Increase) ->
Path = [stock, Wood],
{ok, Stock} = khepri_tx:get(Path),
NewStock = erlang:min(?MAX_STOCK, Stock + Increase),
ok = khepri_tx:put(Path, NewStock).
increase_wood_stock(Wood, Increase) ->
khepri:transaction(
?STORE_ID, fun generic_tx/2, [Wood, Increase]).
```
This way, one can write a more generic transaction function which doesn't rely on variables in its environment, and pass arguments to `khepri:transaction()` instead.
4.  **Stored procedures can be used as transaction functions**. This allows to extract and store a transaction function once and use it many times. This saves the …
=> Support stored procedures as transaction functions

src/khepri_condition.erl, test/conditions.erl
The `is_met/3` function didn't have cases to verify a `#if_has_data{}` condition if the given node was passed as a map of properties instead of a `#node{}` record.
=> khepri_condition: Fix the use of `#if_has_data{}` with node props

src/khepri_machine.erl
`khepri_machine:ack_triggers_execution/2` currently uses a synchronous command to trigger executions but this is unnecessary: triggers are executed asynchronously (via `gen_server:cast/2`) and there aren't any timing concerns that would require a blocking call.
Synchronous commands may fail and crash the `khepri_event_handler` process. In the `triggers` EUnit suite, calls to `khepri_machine:ack_triggers_execution/2` may race with `test_ra_server_helpers:cleanup/1` and the synchronous command might cause an exit within `khepri_event_handler` because the machine is shutting down. This can cause flaky tests in that suite on hardware that is fast enough to lose the race.
In this change, we switch to an asynchronous Ra command for acknowledging trigger executions. Asynchronous Ra commands wil …
=> Acknowledge trigger executions asynchronously

test/app.erl, test/db_info.erl, test/helpers.erl, test/helpers.hrl, test/triggers.erl
Some cases in the EUnit suite emit log messages which interrupt the regular EUnit output and can fill up a terminal page. These changes silence all emitted logs, either by discarding logs or by capturing them and asserting on the contents. The latter is useful in cases like the buggy-sproc case in `triggers`: it's useful to be able to assert on the contents of the error message and ensure that it's counting the number of crashes within the 10 second period.
This will also be useful for a test case in #135
=> Capture and assert on log contents in EUnit tests

src/khepri_path.erl, test/path_operations.erl, test/prop_path_operations.erl
This adds the ability to convert a path such as `[<<>>]` to a string (`"//"` in this case).
URIs can have meaningful consecutive forward slashes. We use this to encode empty binaries in string-based paths. This is breaking change because consecutive forward slashes were ignored before.
Here are a few examples:
* `[<<>>]` = `"//"`
* `[<<>>, <<>>]` = `"///"`
* `[foo, <<>>, bar]` = `"/:foo//:bar"`
* `[foo, bar, <<>>]` = `"/:foo/:bar//`
=> Support empty binaries in string-based paths

src/khepri_fun.erl, src/khepri_machine.erl, src/khepri_utils.erl, test/display_tree.erl
The overview callback formats the state of the machine for functions like `sys:get_status/1`. The actual state of the machine is still accessible with `sys:get_state/1`.
The status output was not very readable because of the beam code binaries in `standalone_fun` records and the use of records for nodes in the internal representation of the tree. This `overview/1` implementation uses the map representation of the tree from `khepri_utils:flat_struct_to_tree/1` and converts compiled standalone functions into regular functions with `erlang:make_fun/3` (which are printed with a more concise and readable format).
=> Implement ra_machine:overview/1 for khepri_machine

src/khepri_fun.erl, src/khepri_tx_adv.erl, test/mod_used_for_transactions.erl, test/tx_funs.erl
Since #149, we resolve and adjust the jump label inside the `call_fun2` instruction. This way we are as close as possible to the code originally produced by the compiler and benefit from its optimizations.
However, there is one situation where we can't keep the jump label: it is when the called local function is not local anymore after extraction.
To avoid many almost identical copies of the same anonymous function where only the environment changes, `khepri_fun` will extract the function in a dedicated module and keep the environment separate. If there is another anonymous function inside this environment, it will become its own module.
Therefore, it's possible that in the original Beam code, the two anonymous functions were inside the same module. If the compiler emitted a `call_fun2` …
=> Fix `call_fun2` instruction jump label support

rebar.config, src/khepri.erl, src/khepri_export_erlang.erl, src/khepri_import_export.erl, src/khepri_machine.erl, test/export.erl, test/export_erlang.erl, test/export_helper.erl
With this patch, it is possible to export and import a Khepri store.
`khepri:export/{2,3,4}` uses a callback module and private data to export the content of the store. It is possible to specify a path pattern to filter what should be exported.
`khepri:import/{2,3}` uses a callback module and private data — of course the same used for export — to import what was previously exported. This function doesn't remove existing tree nodes. It is up to the caller to take care of this. There is no support for filtering on import.
The callback module API is the same as [Mnesia's "Backup and restore" API](https://www.erlang.org/doc/apps/mnesia/mnesia_app_a). The callback module itself doesn't know what is inside the list of "backup items" passed to it, it's completely opaque.
The implementation uses …
=> Add import/export feature

.github/workflows/docs.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml
This follows a warning reported by GitHub Actions:
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16:
actions/checkout, actions/cache
=> GitHub Actions: Update actions/checkout and actions/cache to v3

src/khepri.erl, src/khepri_adv.erl, src/khepri_bang.hrl, src/khepri_tx.erl, src/khepri_tx_adv.erl, test/advanced_delete.erl, test/advanced_tx_delete.erl, test/bang_functions.erl, test/cluster_SUITE.erl, test/simple_delete.erl, test/simple_tx_delete.erl
Likewise for `delete_many_payloads()`, renamed to `clear_many_payloads()`.
This is more readable in the end and helps with completion.
=> Rename `delete_payload()` back to `clear_payload()`

src/khepri_fun.erl
The latest `beam_disasm` (OTP26+) unwraps the type-tag. Registers passed into this function after that change are mistakenly unwrapped, so types like
```erl
#tr{reg = {x, 0}, t = #t_map{super_key = any, super_value = any}}
```
Are mistakenly unwrapped as
```erl
#tr{reg = {x, 0}, t = t_map}
```
Which causes an internal failure in `beam_validator` when passed into `compile:forms/2`.
This change prevents this future breakage by guarding on the type being a tuple. This match should never succeed on OTP26+ since all types in `beam_types.hrl` are specified as records, so the first element will always be an atom.
=> khepri_fun: Add guard for unwrapping type-tagged registers

src/khepri_import_export.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tx_adv.erl, test/export.erl, test/export_erlang.erl, test/keep_while_conditions.erl
This removes one map from the command. This map would have been empty most of the time (about 6 bytes when converted to binary).
=> khepri_machine: Merge `extra` into `options` in `#put{}` command

src/khepri_cluster.erl, test/cluster_SUITE.erl
It is now possible to pass state machine arguments in the Ra server config. This is handy to e.g. set the snapshot interval:
```erlang
RaServerConfig = #{cluster_name => StoreId,
machine_config => #{snapshot_interval => 10000}},
khepri:start(RaSystem, RaServerConfig).
```
=> khepri_cluster: Accept `machine_config` in Ra server config

src/khepri_fun.erl
OTP26 unwraps the min and max information out of the `tr` record's type field, causing this pattern match to fail. Instead we can use the `get_reg_from_type_tagged_beam_register/1` helper to retrieve the register regardless of the type.
=> khepri_fun: Get register from type-tag for call_fun2 translation

test/tx_funs.erl
This test case will ensure that we aren't accidentally losing important bitstring flags once we start handling the OTP26 `bs_match/3` instruction.
=> tx_funs: Test bitstring matching with field flags

doc/overview.edoc
Without this, it is difficult to find out about the feature. Now, this new overview paragraph points the user to the `khepri_import_export` module which gives more details.
Fixes #172.
=> Documentation: Briefly talk about import/export in overview page

src/khepri.app.src, src/khepri_event_handler.erl
We now trap exit signals in `khepri_event_handler`. This is mandatory so that `terminate/3` is called when the supervision tree is shutted down.
=> Fix supervision tree shutdown

src/khepri_cluster.erl, test/db_info.erl
The function verifies that:
1. the local Ra server is running
2. the store ID is known by the local instance of the application
=> khepri_cluster: Add `is_store_running/1` helper

src/khepri_fun.erl, test/fun_extraction_SUITE.erl
To improve the output of common_test in the terminal, Rebar uses [`cth_readable`](https://hex.pm/packages/cth_readable). This library comes with a parse_transform module to convert all calls to `ct:pal()`.
The application modules are thus recompiled on-the-fly (i.e. the result is not written to disk) with this parse_transform. The result is that the module loaded in memory doesn't match the one on disk (different checksums).
This causes the following exception while trying to extract a transaction function. Here is an example:
```erlang
{khepri_ex, failed_to_prepare_tx_fun,
#{error =>
{mismatching_module_checksum,
#{checksum_from_fun =>
<<194,208,71,94,61,101,247,31,220,109,126,242,101,120,40,129>>,
checksum_on_disk =>
<<152,39,250,105,94,89,145,46,251,4,237,114,45,132,63,33>>, …
```
=> khepri_fun: Work around Rebar's use of `cth_readable` parse_transform

src/khepri_machine.erl, test/projections.erl
A deletion to a tree node with children also recursively deletes all of the children tree nodes. Previously, deleted children tree nodes were not deleted from projections. This change looks for all children tree nodes of a deleted tree node and issues projection trigger effects for each deleted tree node.
=> projections: Delete tree nodes recursively

src/khepri_machine.erl
When the Ra machine is restarted and enters the `recovered` state, `restore_projection/3` re-fills the ETS table for each projection given the current tree in the store.
This function also must recreate the ETS table for the projection, though: if the Ra machine has snapshotted the `register_projection` commands, they will not be replayed and the ETS tables for the projections will not be recreated.
=> Recreate ETS tables when restoring projections

.github/workflows/test.yaml, src/khepri_fun.erl, src/khepri_tx_adv.erl, test/tx_funs.erl
This change fixes compatibility with Erlang/OTP 26.0-rc1 release candidate which was cut today: https://github.com/erlang/otp/releases/tag/OTP-26.0-rc1
There are two new instructions: `bs_match/3` and `update_record/5`. `bs_match/3` optimizes some bitstring matching and `update_record/5` is used to update record tuples.
`bs_match/3` replaces some other bitstring matching instructions which are already present in the test suite, so this instruction is already covered while running on Erlang/OTP 26. `update_record/5` can be provoked with a new test case which updates a record field.
=> khepri_tx: Support new Erlang/OTP 26 instructions

src/khepri.erl, src/khepri_adv.erl, src/khepri_condition.erl, src/khepri_import_export.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tree.erl, src/khepri_tree.hrl, src/khepri_tx.erl, src/khepri_tx_adv.erl, test/display_tree.erl, test/keep_while_conditions.erl, test/queries.erl, test/root_node.erl
This change separates tree related functions into a new `khepri_tree` module. `khepri_machine` now focuses on the Ra machine definition and Ra side effects while `khepri_tree` contains the functions for creating and modifying tree nodes and traversing and changing the tree structure.
=> Move tree functions to khepri_tree

src/khepri_tree.erl, test/projections.erl
`khepri_machine` compiles path patterns before traversing the tree in `walk_down_the_tree/6`. Path patterns also must be compiled before checking against paths in `does_path_match/4`.
This fixes a potential crash within `khepri_machine` when a projection is registered to a path pattern containing a condition which must be compiled such as `#if_data_matches{}`.
=> Compile conditions before checking path pattern matching

include/khepri.hrl
The `ets:match_pattern()` type is limited to `atom() | tuple()` for its use against ETS tables but other terms can be valid. For example, when using match specifications in tracing, another form using a list is valid:
```erl
-type match_function() :: {match_head(),
match_conditions(),
match_body()}.
-type match_head() :: '_' |
match_variable() |
[match_head_part(), ...].
-type match_head_part() :: term() | match_variable() | '_'.
-type match_variable() :: atom(). %% '$<n>'
```
`ets:match_spec_compile/1` and `ets:match_spec_run/2` accept just about any term; for example maps:
```erl
MS1 = ets:match_spec_compile([#{hello => foo}, [], [match]]),
MS2 = ets:match_spec_compile([#{hello => bar}, [], [match]]),
[match] = ets:match_spec_run(#{hello => foo}, MS1),
[] = ets:match_spec_run(#{hello => …
```
=> khepri_condition: Broaden pattern type for 'if_data_matches'

src/khepri_machine.erl, src/khepri_tree.erl
This change completes the migration started in #184 which moved functions that acted on the tree structure from `khepri_machine` to `khepri_tree`. With this change, the tree structure can be created and modified without interacting with the machine state. The implementation of `insert_or_update_node/5` is extracted to `khepri_tree` without changes except that the creation of side-effects and the reorganizing of the return value now live separately in `khepri_machine`.
This also allows us to remove a few function exports from `khepri_tree` which were either being called by `insert_or_update_node/5` or were only used internally to `khepri_tree`.
=> Move insert_or_update_node/5 from khepri_machine to khepri_tree

src/khepri.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_pattern_tree.erl, test/helpers.hrl, test/pattern_tree.erl
~Depends on #187~
The main tree structure used to store data in the Khepri store is a tree where each edge is a path component and that tree can look up all matching paths for a given pattern. This change introduces a new tree structure that instead uses pattern components as edges and can be used to look up all matching patterns for a given path.
This replaces the data structure used to hold projections in the machine's state. The prior structure was a mapping from projections to path patterns. Every change to the store was checked against all patterns for registered projections using `khepri_tree:does_path_match/3`. The existing approach is fast in practice but it duplicates some work: pattern components shared between multiple patterns would all be re-compiled and re-checked for each …
=> Store projections in a tree of patterns

src/khepri_machine.erl, src/khepri_machine.hrl
Pattern trees must be compiled with `khepri_pattern_tree:compile/1` before they can be queried into with `khepri_pattern_tree:fold/5`. We can't store the compiled pattern tree in the `khepri_machine` state though because some conditions like `#if_name_matches{}`, `#if_path_matches{}` and `#if_data_matches{}` create runtime-only values during compilation (compiled regular expressions and compiled match specifications) which cannot be serialized/deserialized to/from the Ra log. Currently we recompile the projections pattern tree once per change to the store just before looking up projections with `khepri_pattern_tree:fold/5`. The projections pattern tree changes very infrequently though so this wastes some work.
This change computes the compiled projection pattern tree lazily and stores the …
=> Memoize the compiled projections pattern tree

src/khepri_machine.erl, test/projections.erl
This change fixes a regression introduced with the refactor to the pattern tree to hold projections for a specific case of deletions from the tree tree.
To hit this edge-case, a path must be deleted from the tree with no other sibling tree nodes. In other words, the deletion must not trigger any ancestor tree nodes from being cleaned up by the default keep-while conditions. Also, a projection must be registered to a path pattern which would match this deleted path.
For deletion changes, we look at all of the children of the deleted path to check if child node deletions should trigger any projections. This block mistakenly forgot to also check if the deleted path itself should trigger any projections.
=> projections: Trigger changes for leaf node deletions

doc/_head.html, doc/overview.edoc
We lacked this reference back to the GitHub repository so far.
This ribbon is quite common for GitHub-hosted projects. Here, we use the CSS version of the ribbon:
https://simonwhitaker.github.io/github-fork-ribbon-css/
=> Add a link to the repository as a GitHub ribbon

src/khepri_machine.erl, src/khepri_projection.erl, src/khepri_projection.hrl, test/projections.erl
A common case for projection functions is to re-use each tree node's payload as the record for the projection ETS table. In terms of a simple projection, this is:
```erl
ProjectionFun = fun(_Path, Payload) -> Payload end
```
This change allows passing a special 'copy' atom to stand for this case. When triggering a projection we don't execute a Horus function so 'copy' projections have minimal overhead.
=> Special-case trivial "copy"-style projections

src/khepri_projection.erl, test/projections.erl
ETS calls may fail if a projection function returns a term that can't be inserted or deleted. These should be handled and logged so that they don't crash the `khepri_machine` process.
=> projections: Catch errors from ETS calls

src/khepri_tx.erl, src/khepri_tx_adv.erl
The previous sentence was apparently copy-pasted from another unrelated function.
=> khepri_tx: Fix documentation of the `put()` functions

.github/workflows/test.yaml
We also run Dialyzer from Erlang/OTP 26.
There is still an issue with setup-beam which prevents us from testing with Erlang/OTP 26 on Windows...
=> GitHub Actions: Test against Erlang/OTP 26 stable release

src/khepri_projection.erl, test/projections.erl
The default Horus options used by `khepri_projection:new/3` prevent unintentional non-determinism or interaction between processes. It could be useful to have an escape hatch for this, though. For example you might want to call `persistent_term:get/2` and `persistent_term:put/2` to create some lazy value to use in the projection function.
This change allows passing in `horus:options()` when creating a projection with `khepri_projection:new/2`. These options are merged with the defaults and passed to `horus:to_standalone_fun/2`.
=> projections: Allow passing Horus options

src/khepri_machine.erl
`ra:process_command/3` can now return `{error,shutdown}` if the server shuts down before it replies to the caller (see [here](https://github.com/rabbitmq/ra/pull/388)). We can handle this the same way as the other errors: find a new leader and retry.
=> khepri_machine: Handle shutdown error from ra:process_command/3

src/khepri_utils.erl
If the Khepri application is started and any of the default applications (mnesia, sasl, ssl, and khepri itself) are not available, `application:get_key/2` will return `undefined`, causing a badmatch that will terminate the Khepri application. Instead we can gracefully handle these applications being unavailable and not include their modules in the list of modules to skip when extracting functions.
Fixes #214
=> khepri_utils: Gracefully handle unavailable default applications

src/khepri_cluster.erl, test/db_info.erl
We simply log a debug message and return an empty list.
=> khepri_cluster: Don't log a warning in `query_members()` when store is stopped

src/khepri_cluster.erl, test/cluster_SUITE.erl
If `khepri_cluster:join/1` is called twice in a row, the join succeeds because the joining node is reset before it joins the cluster again. This is not exactly idempotent, but the end result is the same.
However if the joining node was reset somehow (e.g. its data directory was lost) and therefore thinks it is a standalone store, calling `khepri_cluster:join/1` again would return `{error, already_member}`.
It is more comfortable if the function just does what it takes to achieve the wanted result of expanding the cluster.
The `{error, already_member}` error is caught and the function returns `ok` instead. Behind the scene, Ra did the correct thing and the joining node is back in the cluster.
=> khepri_cluster: Make `join/1` idempotent

src/khepri_cluster.erl, test/cluster_SUITE.erl
Reverts rabbitmq/khepri#217
GitHub didn't merge the correct commit: the initial commit (before the review and the updated commit) was merged, not the final accepted one...
=> Revert "khepri_cluster: Make `join/3` idempotent"

src/khepri_cluster.erl, test/cluster_SUITE.erl
If `khepri_cluster:join/3` is called twice in a row, the join succeeds because the joining node is reset before it joins the cluster again. This is not exactly idempotent, but the end result is the same.
However if the joining node was reset somehow (e.g. its data directory was lost) and therefore thinks it is a standalone store, calling `khepri_cluster:join/1` again would return `{error, already_member}`.
It is more comfortable if the function just does what it takes to achieve the wanted result of expanding the cluster.
The `{error, already_member}` error is caught and the function returns `ok` instead. Behind the scene, Ra did the correct thing and the joining node is back in the cluster.
=> khepri_cluster: Make `join/3` idempotent

src/khepri_cluster.erl, test/cluster_SUITE.erl
The initial code followed these steps:
1. It removed the local Ra server from its cluster, if any. It is usually a no-op.
2. It force-deleted the local Ra server and deleted its data on disc.
3. It restarted it without any election.
4. It asked the remote cluster to add the local Ra server as a member.
There is one problem with them if the local Ra server was a member of the remote cluster but it lost its data (for whatever reason). In this case, the local Ra server didn't know about any cluster, but the remote cluster still knew about it. When we tried to join them, depending on the order of events, the remote cluster could send a `append_entries_rpc` message to the local Ra server and the latter could crash with a `leader_saw_append_entries_rpc_in_same_term` exception. The root cause is …
=> khepri_cluster: Fix how we reset a node to join a cluster

src/khepri_machine.erl
Async commands will fail to be applied unless they're sent to the cluster's current leader. With this change we always try to use the cached leader from synchronous commands if available and use the local member if the leader isn't cached. The caller can then update the cached leader value when the async response says that the command was sent against a non-leader member, like so:
```erlang
receive
{ra_event,
FromId,
{rejected, {not_leader, MaybeLeader, CorrelationId}}} ->
ok = khepri_cluster:cache_leader_if_changed(
StoreId, FromId, MaybeLeader),
%% ... retry the command for `CorrelationId' ...
ok
end
```
=> khepri_machine: Use cached leader for async commands

include/khepri.hrl, src/khepri.erl, src/khepri_adv.erl, src/khepri_cluster.erl, src/khepri_cluster.hrl, src/khepri_import_export.erl, src/khepri_machine.erl
This allows to abstract the type of the store ID.
The macro already existed for a long time, but was in a private header. This patch moves it to the public header.
In the process, it is renamed from `?IS_STORE_ID/1` to `?IS_KHEPRI_STORE_ID/1` to reduce the namespace pollution.
=> include/khepri.hrl: Expose `?IS_KHEPRI_STORE_ID/1` macro

src/khepri.erl, src/khepri_adv.erl, test/async_option.erl, test/cluster_SUITE.erl
This is similar to `wait_for_async_ret/1,2` except that the caller is expected to `receive` the Ra event. This is necessary because the Ra event sent when a batch of commands is applied includes a list of correlation and result pairs, making it impossible to use a selective receive to look for a single correlation ID.
We could alternatively map the `ra_event` message into some other value like `{ok, Correlations} | {error, CorrelationId}` but this isn't much easier to work with than the `ra_event`s themselves and would be brittle for changes to `ra_event`. Instead we leave it to the caller to receive and handle the events. This function is then responsible only for calling internal functions to update the cached leader for the given store ID.
I've also added deprecations for …
=> Replace `wait_for_async_ret` with `handle_async_ret` for handling async Ra events

src/khepri.app.src
Previously the two license files wouldn't be published in the Hex package because of their suffixes. We can publish them if we specify the full filenames in the `files` part of the app spec.
=> Hex: Publish license files

src/khepri_cluster.erl
A call to `ra_leaderboard:lookup_members/1` will be faster if it has the answer compared to a Ra server query.
If it doesn't know the list of members, we fall back to the Ra server query.
=> khepri_cluster: Use `ra_leaderboard` first to query members locally

src/khepri_machine.erl
This is not required at this point. However, users can query the machine version without having to worry if the callback is defined (version = 0 when the callback is missing) or not.
We define the first version to be 0.
Depends on rabbitmq/ra#399.
=> khepri_machine: Define the Ra machine version to 0

src/khepri.erl, src/khepri_cluster.erl, test/cluster_SUITE.erl, test/db_info.erl, test/test_ra_server_helpers.erl
Always returning a list, hiding any error behind an empty list, proved to be a bad design, as it made it really difficult to detect errors and act upon them.
This kind of return value was also inconsistent with the rest of the API.
The `members/{0,1,2}`, `locally_known_members/{0,1,2}`, `nodes/{0,1,2}` and `locally_known_nodes/{0,1,2}` functions now return `{ok, List}` or `{error, Reason}`, like other APIs.
The returned list is never empty.
While working on this, the variants taking no arguments were added to work with the default store.
Fixes #243.
=> khepri_cluster: Functions returning members now wrap them in `{ok, Members}`

src/khepri_machine.erl
We want to leave the caller decide the consistency it wants.
Also, there is a problem with leader and consistent queries in Ra because the function is executed on a remote node and the function reference or the MFA may not be valid, leading to an exception.
We just stop setting the `favor` option.
=> khepri_machine: Do not enforce `favor` options in machine state queries

src/khepri_machine.erl, test/helpers.hrl, test/machine_code_called_from_ra.erl
In the future, we will introduce new commands that older versions of the state machine won't know about.
Before this commit, the state machine would crash with a function clause exception. This could be lead to a Ra cluster having a hard time to recover if all Ra servers crash.
If the machine is asked to apply an unknown command, it returns an error. This error is converted to an exception in
`khepri_machine:process_command()`.
While here:
* Add `machine_version` and a valid `system_time` value to the `?META` macro used by tests.
* Fix an invalid log message where arguments to `?LOG_DEBUG()` were incorrect.
**V2**: Log an error using a `mod_call` side effect, not directly from the state machine process using `?LOG_ERROR`. The former solution would log on all Ra cluster members and even …
=> khepri_machine: Handle unknown state machine commands

src/khepri_import_export.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tx.erl, src/khepri_tx_adv.erl, src/khepri_utils.erl, test/cluster_SUITE.erl, test/delete_command.erl, test/keep_while_conditions.erl, test/put_command.erl, test/tx_funs.erl
With the upcoming need to add a field to implement command deduplication, we will have two versions of the record for the machine state.
If we expose the definition, it will be more complicate to track which one we are using.
The record definition is moved to `src/khepri_machine.erl` and made an opaque type.
The module exports functions to access the fields of the record without ever exposing the record itself. Most of these functions were already exported if `TEST` was defined at compile-time. This is no longer needed.
=> Make `#khepri_machine{}` private

src/khepri_machine.erl
… instead of using the record directly.
This is a preparation step for a future update of the record. At that point, there will be two versions of the state record to support and it's easier to isolate that handling in a few functions.
All reads and writes to the state go through a set of `get_*/1` and `set_*/2` functions.
=> khepri_machine: Use functions to manipulate the internal state

src/khepri.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_pattern_tree.erl, test/cluster_SUITE.erl, test/projections.erl
`khepri_machine` shouldn't initialize projections in its `apply/3` callback. That function might be called by Ra when recovering and folding through the log from a snapshot. If the log contains a `#register_projection{}` command then Khepri will mistakenly create the ETS table and fill it with whatever is in the tree at that moment. Effects like `#trigger_projection{}` are discarded during recovery, so restarting a server could lead to inconsistencies in projection tables between cluster members.
Instead we can use an aux effect to perform the side effects like we do already for `restore_projections` and `#trigger_projection{}` effects. This will be correctly discarded when Khepri is recovering. Then projections will be correctly restored once the machine is recovered with the existing …
=> Use effects to initialize new projections

src/khepri_pattern_tree.erl, test/pattern_tree.erl, test/projections.erl
A pattern tree with `/parent/*` is supposed to match `/parent/child` but not `/parent/child/grandchild`.
Before this patch, this was the case because we didn't check if we reached the of the path before calling the folding function in `khepri_pattern_tree:fold1/6`.
Now, we check the context and only call the fold function if we reached the end of the path.
Otherwise, we recurse without calling that fold function, checking a few more things depending on whether the condition could match grand children or not.
The testsuites are expanded with more testcases to cover these situations.
=> khepri_pattern_tree: Fix conditions that were matching subtrees

src/khepri.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_machine_v0.erl, src/khepri_tx_adv.erl, test/cluster_SUITE.erl, test/helpers.erl, test/protect_against_dups_option.erl, test/tx_funs.erl
The "client" side of `khepri_machine` implemented in `process_sync_command/3` have a retry mechanism if `ra:process_command/3` returns an error such as `noproc`, `nodedown` or `shutdown`.
However, this retry mechanism can't tell if the state machine already received the command and just couldn't reply, for instance because there is a node stopping or a change of leadership.
Therefore, it's possible that the same command is submitted twice and thus processed twice.
That's ok for idempotent commands, but it may not be alright for all transactions for example. That's why we need a deduplication mechanism that ensures the same command is not applied multiple times.
Two new commands are introduced to implement the deduplication system:
* `#dedup{}` which is used to wrap the command to protect …
=> khepri_machine: Add command deduplication mechanism

src/khepri_cluster.erl, test/cached_leader.erl
Local or leader queries may return `not_known` instead of the leader ID if this one isn't known as part of the query.
So far, we cached that value and this value was used as the leader ID in follow-up calls to Khepri... This is incorrect as this is clearly not a valid Ra server ID.
If the passed "leader" ID is `not_known`, we ignore it and don't cache anything.
We don't clear the cached leader either because we lack context to take that decision.
=> khepri_cluster: Don't cache the `not_known` "leader"

.github/workflows/docs.yaml, .github/workflows/test.yaml
The installer fails to work or the way `setup-beam` uses is incorrect.
```
Installing Erlang/OTP 26.2.5.2 - built on amd64/windows-2022
D:\a\_temp\.setup-beam\otp\otp.exe /S /D=D:\a\_temp\.setup-beam\otp
Action install Erlang/OTP 26.2.5.2 failed for mirror https://builds.hex.pm, with Error: The process 'D:\a\_temp\.setup-beam\otp\otp.exe' failed with exit code 2
```
While here, stop testing against Erlang/OTP 24 to save ressources.
=> GitHub Actions: Skip Erlang/OTP 26.2.5.2 on Windows

include/khepri.hrl
The previous version was too basic and would not be able to distinguish a Khepri path condition from any tuple.
We test explicitly each condition record.
=> include/khepri.hrl: Make `?IS_KHEPRI_CONDITION/1` stricter

include/khepri.hrl, src/khepri_error.hrl
They are useful for users of Khepri to match return values and exceptions.
The macro definitions are moved from `src/khepri_error.hrl` to `include/khepri.hrl`.
`src/khepri_error.hrl` now includes `include/khepri.hrl` to get the definitions it uses. `include/khepri.hrl` is protected against multiple inclusions in the process.
=> include/khepri.hrl: Export `?khepri_error/2` and `?khepri_exception/2`

test/cluster_SUITE.erl
The testcase was issueing a put on node 1, then a get on all nodes. From time to time, one of the gets would fail because the queried node didn't see the put yet.
Now, we use the `#{favor => consistency}` option for gets on nodes that are neither the leader, nor the follower that issued the put.
Indeed, to increase the testing of consistency, we also perform the put from a follower instead of node 1.
This is the same fix as committed in commit a076a83 (#269) for another testcase.
=> cluster_SUITE: Fix `handle_leader_down_on_three_node_cluster_command/1` testcase

src/khepri_machine.erl
`reply_from` is ineffective in the first place in this case because `process_command/3` could have sent the command to the leader directly.
Leave `process_command/3` set `reply_from`. By default, it will use the local member ID. This is the same intention than `local` but it will work regardless of the node that the command is sent to.
=> khepri_machine: Don't set `reply_from` when (un)registering projections

src/khepri_cluster.erl, test/db_info.erl
If a Ra server has stopped behind the back of Khepri, the `is_store_running/1` and `get_store_ids/0` function will return incorrect data or even hit an assertion.
With these commits, the list is automatically cleaned up if one of the functions detects that a stopped Ra server is still listed.
Fixes #271.
=> Automatically clean the list of running stores if a Ra server has stopped behind the scene

test/test_ra_server_helpers.erl
The parameter was removed in commit 982f17d326514fc144ed67257e846b578e440c9f (as part of #260).
=> test: Don't set `consistent_query_interval_in_compromise`

src/khepri_export_erlang.erl, test/export_erlang.erl
The `file:name_all()` type accepts atoms and binaries in its definition.
Also, Elixir strings are binaries really, so using `"filename.erl"` as the filename would break because the module would consider that binary filename as an already opened file descriptor.
The guard expression is expanded to accept atoms and binaries.
Fixes #278.
=> khepri_export_erlang: Accept atoms and binaries as filenames

test/cluster_SUITE.erl
The testcases were issueing a put on node 1, then a get on all nodes. From time to time, one of the gets would fail because the queried node didn't see the put yet.
Now, we use the `#{favor => consistency}` option for gets on nodes that are neither the leader, nor the follower that issued the put.
Indeed, to increase the testing of consistency, we also perform the put from a follower instead of node 1.
This is the same fix as committed in commit a076a83 (#269) for another testcase.
=> cluster_SUITE: Fix remaining consistency issues

src/khepri.erl, src/khepri_adv.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_pattern_tree.erl, src/khepri_projection.erl, test/cluster_SUITE.erl, test/projections.erl
The motivation for this in RabbitMQ is that we currently mistakenly register projections even when using mnesia as the metadata store in 3.13.x. It's a benign mistake - it shouldn't have much impact on those running 3.13.x - but it will be a potential headache for upgrading to 4.0.x since we also plan on reorganizing the tree layout (see https://github.com/rabbitmq/rabbitmq-server/pull/11225). With this change we will be able to use `khepri:unregister_all_projections/0` as we enable the `khepri_db` flag to remove those projections and add fresh definitions.
Implementation-wise the change is very straightforward: it's a new `#unregister_all_projections{}` command which calls `khepri_projection:delete/1` for each deleted projections and returns a map of the deleted projections (for …
=> Replace `unregister_projection` command with `unregister_projections`

src/khepri_machine.erl
This pull request is a collection of patches that improves the performances of the fence mechanism.
It uses `ra:key_metrics/2` instead of `ra:member_overview/2` and avoids the preliminary query that we do to serialize events if it is not needed. See individual commits for more details.
This pull request is blocked because it depends on a new release of Ra that contains rabbitmq/ra#461. Also, to fully fix the performance problem introduced with the fence mechanism, we also need that that future release of Ra contains rabbitmq/ra#462.
=> Improve the fence mechanism performances

src/khepri_machine.erl, src/khepri_machine.hrl, test/projections.erl
Even though this version of Khepri never emits `#unregister_projection{}`, existing WAL files may still contain that command.
To not break these existing deployment, `apply/3` accepts `#unregister_projection{}` again. It converts it to the new `#unregister_projections{}` command and recurses.
=> khepri_machine: Restore `#unregister_projection{}` for backward-compatibility

src/khepri_cluster.erl, src/khepri_cluster.hrl, src/khepri_machine.erl, test/cluster_SUITE.erl
This pull request contains a set of patches to fix the functions to query Ra members and nodes in `khepri_cluster`:
* The return value in case of a timeout was not aligned with the type spec and inconsistent with what other functions do.
* The timeout argument may not have been honored in the case of a `noproc`.
* The query was not retried after a `noconnection` error and a few other related errors.
=> Fixes to `khepri_cluster` member queries

src/khepri_cluster.erl, test/cluster_SUITE.erl
This new public API is useful if you want to be sure a clustered store is ready before issueing writes and queries.
Note that there are obviously no guaranties that the Raft quorum will be lost just after this call.
The implementation is very close to `members/{0,1,2}`. The difference are:
* how errors are handled
* the return value
=> khepri_cluster: Add `wait_for_leader/{0,1,2}`

src/khepri_machine.erl, src/khepri_tx_adv.erl, test/projections.erl
This is an optimization for functions in the transaction APIs. Specifically this should be very noticeable when any command from the `khepri_tx` or `khepri_tx_adv` API (delete, put, etc.) is used with a pattern that affects very many nodes (10,000 or more). The gist is that we can get surprisingly nice speed ups for some functions by building our side effect lists with `[Effect | Effects]` rather than `++/2`.
For background: I have WIP changes to simplify the exchange deletion part of vhost deletion in RabbitMQ by using a transaction ([commit](https://github.com/rabbitmq/rabbitmq-server/commit/2763111bf6e9)). It deletes all exchanges and bindings in a single command without adding/removing runtime parameters and returns the combined `rabbit_bindings:deletions()` dict. It also changes the …
=> khepri_tx_adv: Prefer list prepending to build side effect lists

src/khepri_cluster.erl
The previous use of `ra:ping/2` was too expensive.
As
`khepri_cluster:is_store_running/1` is now used by `mnesia_to_khepri:is_migration_finished/2` and
`mnesia_to_khepri:hande_fallback/5` since khepri_mnesia_migration 0.6.0, we saw a regression in performance in RabbitMQ because of this.
khepri_mnesia_migration was using a very basic and incomplete version of `is_store_running()` before. That's why the issue was not spotted earlier.
The new code uses `ra:key_metrics/2` which simply checks if the process us running and query a few local counters. This is way faster because it does not send messages to the Ra server.
=> khepri_cluster: Use key metrics to determine if a Ra server is running

src/khepri_projection.erl, test/cluster_SUITE.erl
The test case in this change shows an example that can cause an error log. One client of Khepri sends an `unregister_projections` command while another sends many changes which affect a projection which is being unregistered. Using async commands makes the error much more likely to occur.
Ra applies committed commands in a batch and then handles all effects created by the batch. In this scenario the `unregister_projections` command may end up being applied by Ra in a batch with the async commands and the resulting effects list will contain aux effects to trigger projections (casued by the async commands) and an aux effect to unregister the projection. Some trigger aux effects may come later in the list than the `unregister_projections` effect and so their projection table will be deleted. …
=> Handle deleted projections tables while triggering projections

src/khepri_cluster.erl
The `khepri_cluster:reset()` function is mainly used to uncluster a node. To make sure that both parties (the leaving node and the rest of the cluster) see the same cluster membership in the end, we perform two resets:
1. We remove the leaving member from a remote member (if the node is clustered).
2. We remove the leaving member from its own view of the cluster.
This way, if the leaving node was out-of-sync about the cluster membership because it lost its state for instance, we are sure that at the end, everyone agrees.
However, when the leaving node is removed using a remote member, that member will stop the leaving Ra server. Therefore, when we try the second remove on the leaving node, we might get a `{error, noproc}` error because the Ra process already exited.
We adopt the same …
=> khepri_cluster: Fix race condition in the reset code

src/khepri_cluster.erl
If a cluster change (a member joining or leaving), it is not permitted to make another change: Ra will reply with the following error:
```erlang
{error, cluster_change_not_permitted}
```
Before this patch, we would retry immediately after such an error. We were effeclively spamming the Ra server with many join/leave commands, but the user too with hundreds of "not ready; waiting..." log messages.
For now, we simply add a hard-coded 200 ms sleep before retrying.
=> khepri_cluster: Stop spamming cluster with join/leave if it is not ready

src/khepri_cluster.erl
A store's process uses its `StoreId` as its registered name. This is a public interface of Ra so we can depend on it. Reading from key metrics counters is already very fast but switching to `whereis/1` eliminates basically all overhead of this function. When used heavily (for example in RabbitMQ while publishing and consuming rapidly) the CPU time spent on `is_store_running/1` disappears from the output of a perf recording and a flamegraph.
This is a follow-up to https://github.com/rabbitmq/khepri/pull/292 based on the post-merge discussion.
=> Use `erlang:whereis/1` for checking if a store is running

src/khepri_machine.erl, src/khepri_machine_v0.erl, src/khepri_prefix_tree.erl, src/khepri_tree.erl, test/keep_while_conditions.erl, test/pattern_tree.erl, test/prefix_tree.erl
When handling a deletion, `khepri_tree:eval_keep_while_conditions/2` folded over the reverse index of keep while conditions and evaluated any for which the removed path was a prefix. This meant folding over each non-leaf node in the tree. We can eliminate nodes very quickly though to limit the impact of this search by using a prefix tree instead.
This change switches out the `keep_while_conds_revidx` field in `#khepri_tree{}` to a new `khepri_prefix_tree` type when the Khepri cluster reaches the new effective machine version of 2.
=> Replace keep-while cond reverse index with a prefix tree

src/khepri_cluster.erl, test/cluster_SUITE.erl
It will be easier to work with the `khepri_cluster:members()` and `khepri_cluster:nodes()` functions if they take the same arguments as queries of the store.
The `Timeout` argument is replaced with a map of query options, the same as store queries. It supports the `timeout` and `favor` options. In particular, the `favor` option indicates if the query should be sent to the leader or the local Ra server.
The `khepri_cluster:locally_known_*()` variants became irrelevant and were deleted.
=> khepri_cluster: Unify `members()` and `nodes()` with other query APIs

.github/workflows/test-and-release.yaml, rebar.config
Khepri docs fail to build with Erlang/OTP 27.1. This came from a new callback expected by xmerl that rebar3_edoc_extensions did not define. This was fixed in vkatsuba/rebar3_edoc_extensions#28 and released in rebar3_edoc_extensions 1.6.1.
While here, add new CI steps to detect `rebar3 edoc` early (it doesn’t exit with an error…).
=> Fix generation of docs with Erlang 27

src/khepri.erl, src/khepri_adv.erl, src/khepri_projection.erl, src/khepri_ret.hrl, src/khepri_tx.erl, src/khepri_tx_adv.erl, src/khepri_utils.erl, test/advanced_delete.erl, test/advanced_get.erl, test/advanced_put.erl, test/advanced_tx_delete.erl, test/advanced_tx_get.erl, test/advanced_tx_put.erl, test/async_option.erl, test/cluster_SUITE.erl
Functions such as `khepri_adv:get()` and `khepri_adv:put()` extracted the single node's properties from the query/command return value and returned only that.
Therefore, the return value had a different form than other advanced functions' full node properties map.
In a future patch, we want to add the nodes deleted by the "expiration" of `keep_while` conditions. They can be deleted after a delete or a put. If we want to achieve that, we need to make all functions return the same thing.
All functions that returned the single node props value are simplified to return the whole map, regardless of the number of tree nodes in the map.
=> khepri_adv, khepri_tx_adv: Always return `khepri_adv:many_results()`

src/khepri.erl, src/khepri_adv.erl, src/khepri_node.hrl, src/khepri_tree.erl, test/advanced_delete.erl, test/advanced_tx_delete.erl, test/async_option.erl, test/cluster_SUITE.erl, test/delete_command.erl, test/keep_while_conditions.erl, test/prop_state_machine.erl
This change adds a `delete_reason` prop to the props map for nodes deleted with a function from the adv APIs `khepri_adv` and `khepri_adv_tx`. Tree nodes which are the target of deletion commands gain a `delete_reason` property set to `direct`. This change also includes any tree nodes which were deleted because of an expired keep-while condition in the node props map. These expired nodes have a `delete_reason` property set to `keep_while` instead. The `delete_reason` property lets callers filter on whether a change was a deletion and distinguish nodes deleted directly or indirectly.
=> khepri_adv: Add `delete_reason` prop, accumulate keep-while expirations

src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_projection.erl, test/protect_against_dups_option.erl, test/test_ra_server_helpers.erl
This change moves the work we do in `khepri_machine:drop_expired_dedups/2` out of `apply/3` and into the handler for Ra's periodic `tick` aux effect.
The commit message has more details but the TLDR is that the `maps:filter/2` within `drop_expired_dedups/2` can become expensive if many transactions are being handled before their dedups are received. Instead we can determine if any dedups are expired in the handler for the `tick` effect and expire any by committing a new `#expire_dedups{}` command.
Also included is a change to use the new `handle_aux/5` API introduced in Ra 2.10 but that change shouldn't have any effect on behavior.
=> Expire dedups on `tick`

src/khepri.erl, src/khepri_tree.erl, test/queries.erl
A future version of Khepri might introduce new props to return. If a Khepri cluster is being upgraded and several versions of the Khepri machine are running at the same time, an old node could be called with props to return it doesn’t know.
We simply ignore unknown props.
In the process, we ignore `delete_reason` because it is set by another part of the code anyway.
=> khepri_tree: Ignore unknown props to return

src/khepri_machine.erl, src/khepri_tx.erl, src/khepri_tx_adv.erl
The `delete_reason` property to return was introduced with machine version 2. Older versions have two issues:
* They don't know this property
* They crash on unknown properties
We request this new property only if the effective machine version is greater or equal to 2 to avoid the issues listed above.
Future unknown properties are ignored since commit 257cf328110a69618ad0cf35e3ea1c5bb2a40e4c merged in the previous pull request #308.
=> khepri_machine: Request `delete_reason` if effective machine version >= 2 only

src/khepri_tx_adv.erl
Transactions might use functions like `khepri_path:combine_with_conditions/2` to modify a path from the env with extra conditions like checking the version. `khepri_path` functions are all pure - with the exception of `compile/1`, but compiling regexes within a transaction for example should be harmless - so we should allow these within transactions.
=> khepri_tx_adv: Allow calls to `khepri_path` in transactions

src/khepri_cluster.erl
The rework of the `khepri_cluster:members/2` to make the API close to other functions saw the drop of the call to the `ra_leaderboard`. This call was an optimization.
The function is simply modified to restore the call to `ra_leaderboard` if the query is a local one.
=> khepri_cluster: Restore the use of `ra_leaderboard` in `members/2`

src/khepri_machine.erl
In particular, the return value of `can_skip_fence_preliminary_query/1` was incorrectly documented.
=> khepri_machine: Fix some comments on the fence mechanism

src/khepri_machine.erl
There was a small bug with our use of the persistent_term: it should have been a key per store ID and process PID combination, not just per store ID.
But anyway, a persistent_term is designed for a value that is mostly read, rarely written to. This was not the case here.
I thought about using an ETS table instead but it had a problem: if the calling process is on a different node that the one running Khepri, Khepri can't create an ETS table on that remote node. Each call could initialize that table if it didn’t exist, but this would be too much overhead in that code path to my taste. Moreover, we would have to put in place a cleaning mechanism for processes that exited if they still had an entry in that ETS table.
The solution retained is the use of the calling process dictionary. It is …
=> khepri_machine: Use process dict instead of `persistent_term` to track the need for a fence preliminary query

src/khepri_tx.erl, src/khepri_tx_adv.erl, test/cluster_SUITE.erl, test/tx_funs.erl
The transaction code is compiled on one Erlang node with a specific version of Khepri. However, it is executed on all members of the Khepri cluster. Some Erlang nodes might use another version of Khepri, newer or older, and the transaction API may differ there.
For instance in Khepri 0.17.x, the return values of the `khepri_tx_adv` functions changed. The transaction code will have to handle voth versions of the API to work correctly. Thus it can use this function to adapt its behaviour.
The first transaction version is set to 1 and is exported as a public API.
A transaction use can use it it determine how to use the `khepri_tx` and `khepri_tx_adv` modules and what to expect in terms of behaviour and return values.
=> khepri_tx: Export the transaction API version

src/khepri_machine.erl
It is based on the machine version but it used the latest supported one. The problem is that the dedup mechanism was added to version 1, not necessarily the latest.
Therefore, the existing check would skip the use of the dedup mechanism just because the effective machine version was not the latest one.
We check that the effective version is at least 1, the version where the deduplication mechanism was added.
=> khepri_machine: Fix dedup mechanism support check

src/khepri_machine.erl
This makes sure only query or command options are really passed down to these functions.
=> khepri_machine: Filter options before passing them to `read*_transaction/4`

src/khepri_machine.erl, src/khepri_tree.erl, test/keep_while_conditions.erl, test/triggers.erl
A tree node couldn’t depend on the absence of another node because:
* The `#if_node_exists{exists = false}` condition was evaluated to false if the target tree node didn’t exist like all other conditions.
* `keep_while` conditions were not evaluated for freshly created nodes.
This made it impossible to do something like:
```erlang
khepri:create(
StoreId, [bar], bar_value,
#{keep_while => #{[foo] => #if_node_exists{exists = false}}})).
```
=> Fix two issues with `keep_while` conditions

src/khepri_machine.erl, test/simple_tx_get.erl, test/simple_tx_put.erl
We used `split_{query,command}_options()` to extract relevant options to pass to the transaction implementation. However these `split_*()` functions are strict and they will raise an exception if a query option is mixed with a command option.
This is impracticle with "auto" transactions that could be queries or writes.
In the context of auto transactions, we remove query options before we extract command options, or the opposite. This way, we are sure the the `split_*()` function will not raise an exception.
=> khepri_machine: Fix query/command options filtering for transactions

test/cluster_SUITE.erl
We perform a get on all nodes after writing to one of them. It happens in CI that the write is not applied everywhere yet.
We perform the get with the favor option set to `consistency` to make sure that the latest leader command was appied locally.
=> cluster_SUITE: Improve reliablitily of `can_join_several_times_a_three_node_cluster`

src/khepri.erl, src/khepri_machine.erl, src/khepri_machine.hrl, src/khepri_tree.erl, src/khepri_tx.erl, src/khepri_tx_adv.erl, test/cluster_SUITE.erl, test/delete_command.erl, test/keep_while_conditions.erl, test/protect_against_dups_option.erl, test/put_command.erl, test/return_indirect_deletes_option.erl, test/root_node.erl, test/simple_get.erl, test/tx_funs.erl
In Khepri cluster, a transaction function is submitted by one member and executed on all members. All runs of that function must reach the same output state from the same input.
We made several changes to refine the API since Khepri 0.16.0:
* #303: return values of the advanced API were unified.
* #305: all indirectly deleted tree nodes are returned in the return values of put and delete advanced commands, and the delete reason was added to each deleted tree node.
These are breaking changes in both the "regular" and the transaction APIs. For the regural API, that is ok, because the state machine code itself remained compatible with older versions. Only on formatting of the return value was affected and that formattion is local to the caller (except in the case of an RPC call, but that’s …
=> Fix transactions backward compatibility with older Khepri

src/khepri_tx_adv.erl, test/cluster_SUITE.erl
In an issue reported by a RabbitMQ user, the timeout passed to `khepri_cluster:wait_for_leader/2` may not have been honored. We are not sure of that because we lack information from this user. But this timeout was not covered by a test case before.
The new test case starts a single-node store, runs several slow transactions that take 40 seconds overall, then restarts the store twice. The restart returns immediately but behind the scene, it takes 40 seconds again to replay the transactions during recovery.
After the first restart, we call `khepri_cluster:wait_for_leader/2` with a timeout of 60 seconds. It returns successfully after 40 seconds.
After the second restart, we call the function again but with a timeout of 30 seconds. This time, it returns `{error, timeout}` after 30 seconds as …
=> cluster_SUITE: Add a timeout handling test case

src/khepri_cluster.erl
If the reset occurs at the same time the Ra process is exiting, it could return `{error, normal}`, `normal` being its exit reason probably.
It should be handled the same way as `{error, noproc}` which corresponds to an already exited Ra process.
=> khepri_cluster: Handle `{error, normal}` in do_reset/4

src/khepri_cluster.erl
The code was reading the persistent term, adding/removing a key and writing the persistent term again.
When several stores are started and/or stopped in parallel, these unprotected concurent read/modify/write operations could cause some store properties to be lost in the process.
The code now acquires a local lock before proceeding with this read/modify/write.
=> khepri_cluster: Acquire lock before doing a read/modify/write on ?PT_STORE_IDS

src/khepri_cluster.erl, test/cluster_SUITE.erl, test/helpers.erl
It allows to:
1. detect some race conditions or other concurrency isues
2. run tests faster
This branch organizes test cases in groups to allow to run them in parallel.
It contains several fixes to tests, discovered in the process.
=> Run common_test in parallel

src/khepri_import_export.erl, src/khepri_machine.erl, src/khepri_machine_v0.erl, src/khepri_path.erl, src/khepri_tree.erl
This is a collection of fixes of warnings reported by Dialyzer in Erlang/OTP 28.
These are not reported on CI yet because we can’t test against Erlang/OTP 28 until a new release of Rebar is published with the fix to make it work on Windows (erlang/rebar3#2954).
=> Fix Dialyzer warnings

.github/workflows/test-and-release.yaml, .github/workflows/test-job.yaml
While here, bump Rebar version from 3.23.0 to 3.25.1.
=> GitHub Actions: Test against Erlang/OTP 28

src/khepri.erl
The spec indicated that the options could be `tree_options()` which was incorrect. The options can only be `command_options()`.
=> khepri: Fix spec of `register_trigger/{4,5}`
